In [1]:
import torch

## Generate 1D tensor from a list

In [76]:
x1 = torch.tensor(2)
print (x1.dtype)

torch.int64


In [79]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [80]:
a = torch.tensor([i for i in range(5)])

In [81]:
print (a)

tensor([0, 1, 2, 3, 4])


In [82]:
a.dtype, a.type()

(torch.int64, 'torch.LongTensor')

In [83]:
a = torch.tensor([float(i) for i in range(5)])
print (a, a.dtype, a.type())

tensor([0., 1., 2., 3., 4.]) torch.float32 torch.FloatTensor


#### accessing elements

In [85]:
a[2], a[2].item(), type(a[2].item())

(tensor(2.), 2.0, float)

### size of tensor

In [12]:
a.size(), a.ndimension()

(torch.Size([5]), 1)

In [ ]:
[[[]]]

In [88]:
print (a)
print (a.size())

tensor([0., 1., 2., 3., 4.])
torch.Size([5])


### changing view of tensor

In [89]:
## lets change 1D tensor to 2D tensor
a_view = a.view(5,1)
print (a)
print (a_view)
print (a.size(),a.ndimension())
print (a_view.size(),a_view.ndimension())

tensor([0., 1., 2., 3., 4.])
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])
torch.Size([5]) 1
torch.Size([5, 1]) 2


In [90]:
a.view(5,1,1).shape

torch.Size([5, 1, 1])

##### Numpy to Tensor and Vice-Versa

In [16]:
import numpy as np

In [91]:
## convert numpy to tensor
a_np = np.arange(1.0,3.5,0.5)
a_tensor_from_np = torch.from_numpy(a_np)
print (a_np, a_tensor_from_np)
print (a_tensor_from_np.type())

[1.  1.5 2.  2.5 3. ] tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000], dtype=torch.float64)
torch.DoubleTensor


In [92]:
## convert tensor back to numpy
a_numpy_from_tensor = a_tensor_from_np.numpy()
print (a_numpy_from_tensor)

[1.  1.5 2.  2.5 3. ]


## Math Operations in Torch

In [93]:
## addition
u = torch.tensor([0,1])
v = torch.tensor([1,0])
w = u + v
print (w)

tensor([1, 1])


In [94]:
## multiplication
y = torch.tensor([[1],[3]])
z = 1.5*y
print (z)

tensor([[1.5000],
        [4.5000]])


In [95]:
## elementwise product
u = torch.tensor([1,2])
v = torch.tensor([-2,3])
w = u*v
print (w)

tensor([-2,  6])


In [96]:
## linear combination
u = torch.tensor([1,2])
v = torch.tensor([-2,3])
w = 2*u + 3*v
print (w)

tensor([-4, 13])


In [99]:
## dot product
u = torch.tensor([1,2])
v = torch.tensor([-2,3])
w = torch.dot(u,v) ## -2+6 = 4
print (w)

tensor(4)


### Broadcasting - adding scalar to vector

In [101]:
z = v + 10  ## [[-2, 3],[4,6]] + [[10, 10],[10,10]]
print (z)

tensor([ 8, 13])


### Working with 2D tensors

In [102]:
lst_of_lst = []
for i in range(3):
  lst = []
  for j in range(3):
    lst.append(10*(i+1) + j)
  lst_of_lst.append(lst)

lst_of_lst = torch.tensor(lst_of_lst)
print (lst_of_lst)

tensor([[10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]])


In [103]:
## slicking and indexing matrix elements
a = lst_of_lst
print (a)
print ('######')
print (a[0,0].item(),a[2,2].item())
print (a[1,1:3])
print (a[:,1:3])
print (a[:2,1:3])

tensor([[10, 11, 12],
        [20, 21, 22],
        [30, 31, 32]])
######
10 32
tensor([21, 22])
tensor([[11, 12],
        [21, 22],
        [31, 32]])
tensor([[11, 12],
        [21, 22]])


In [105]:
## matrix multiplication:  2*3 * 3*2 = 2 * 2
a = torch.tensor([[3.,4.,-2.],[1.,-6.,8.]])
b = torch.tensor([[-1.,4.,2.],[4.,2.,6.]])
c = torch.tensor([[-1.,2.],[2.,6.],[8.,3.]])

In [106]:
d = a*b
e = a.mm(c)
print (d)

tensor([[ -3.,  16.,  -4.],
        [  4., -12.,  48.]])


In [107]:
print (e)

tensor([[-11.,  24.],
        [ 51., -10.]])


In [108]:
## inverse
torch.inverse(e)

tensor([[0.0090, 0.0215],
        [0.0458, 0.0099]])

In [109]:
torch.det(e)

tensor(-1114.)